#!/usr/bin/python3

line1_count = 0
a = "SCHL"
line1_count += 1

line2_count = 0
b = "SCHL"
line2_count += 1

line3_deleted = "No"
del a

line4_deleted = "No"
del b

line5_count = 0
c = "SCHL"
line5_count += 1

with open("string_line1.txt", "w") as file:
    file.write(str(line1_count))

with open("string_line2.txt", "w") as file:
    file.write(str(line2_count))

with open("string_line3.txt", "w") as file:
    file.write(line3_deleted)

with open("string_line4.txt", "w") as file:
    file.write(line4_deleted)

with open("string_line5.txt", "w") as file:
    file.write(str(line5_count))

